steps:
  - label: Build the docker environment
    command: make dockerenvbuild

  - wait

  - label: Build the python packages
    command: mkdir -p dist && .buildkite/build_whl.sh && docker container prune -f


  - label: Build the pex file
    command: mkdir -p dist && .buildkite/build_pex.sh

