script: phantomjs test/runner.js test/index.html
notifications:
  on_success: change
  on_failure: always
  hipchat:
    rooms:
      # Content tools
      secure: XFtzoGC0qGndavcb7A/TtL90bTmtHhKsQRmalGSxPwCO2HCkXT6VY4A3r1zRLXqR/k5mBvxoEB0OgXm3FdwmBFVYkoCIJ/CqxZbZjoKY0i1pwrRy0oP58uVPUpEDtSCwBHvQhEKiSVtSgQhlgvijpjCmFOoC+zKVCz8W2LAi938=
